<a href="https://colab.research.google.com/github/megha-2002/Let-s-Upgrade/blob/main/Day1_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [7]:
Arr=np.random.randint(-10,10,(1,5))
Arr

array([[ 9, -4, -1, -5,  1]])

In [9]:
D=np.array(range(18)) + 3
D

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [32]:
for i in range(2,10):
  x=D[i]
  print(x,end=" ")

5 6 7 8 9 10 11 12 

In [31]:
for i in range(10,2,-1):
  y=D[i]
  print(y,end=" ")

13 12 11 10 9 8 7 6 

In [30]:
z = D[::-1]
print(z)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3]


**3. How are NumPy Arrays better than Lists in Python?**

They are very much convenient to use as it contains many inbult functionalities. It consumes less memory and is fast as compared to lists.

**4. Explain the data types supported by Numpy.** 

i - integer

b - boolean

f - float

O - object

S - string

are some of the most commonly used datatyped in numpy. 

u - unsigned integer

c - complex float

m - timedelta

M - datetime

U - unicode string

V - fixed chunk of memory for other type ( void )

are also used in necessory cases.

**INDEXING PROBLEM-PRACTICE**

In [4]:
a= np.random.randint(10,50,(5,5))
a

array([[29, 42, 47, 11, 13],
       [43, 28, 16, 24, 49],
       [22, 27, 12, 43, 44],
       [42, 44, 32, 31, 37],
       [48, 36, 42, 34, 22]])

In [5]:
## printing 42, 27,
##          37, 16
a[1:3,3:]

array([[24, 49],
       [43, 44]])

In [6]:
## printing 13, 47, 42,
##          33, 44, 37
a[1:3,1:4]

array([[28, 16, 24],
       [27, 12, 43]])