<a href="https://colab.research.google.com/github/megha-2002/Let-s-Upgrade/blob/main/Day1_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a= np.random.randint(10,50,(5,5))
a

array([[46, 26, 32, 20, 36],
       [15, 13, 47, 42, 27],
       [40, 33, 44, 37, 16],
       [48, 44, 30, 39, 18],
       [18, 33, 14, 26, 39]])

In [12]:
## printing 42, 27,
##          37, 16
a[1:3,3:]

array([[42, 27],
       [37, 16]])

In [48]:
## printing 13, 47, 42,
##          33, 44, 37
a[1:3,1:4]

array([[13, 47, 42],
       [33, 44, 37]])